---
# use global vars or local vars
- set_fact:
    npmPath: '{{ npm_path if ((global_npm_path is not defined) or (global_npm_path|length == 0)) else global_admin_password }}'

- name: Create directory structure
  ansible.windows.win_file:
    path: '{{ npmPath }}'
    state: directory

- name: Configure npm prefix path
  ansible.windows.win_shell: npm config set prefix {{ npmPath }}

- name: Install yarn
  ansible.windows.win_shell: npm install --global yarn

- name: Get stdout or stderr from the output
  debug:
    msg:
      - '{{ npmPath }}{{ var_yarn }}'
- name: Ensure that path is on the global PATH
  win_path:
    elements:
      - '{{ npmPath }}'
