---
- name: Create directory structure
  ansible.windows.win_file:
    path: '{{ npm_path }}'
    state: directory

- name: Configure npm prefix path
  ansible.windows.win_shell: npm config set prefix {{ npm_path }}

- name: Install yarn
  ansible.windows.win_shell: npm install --global yarn

- name: Get stdout or stderr from the output
  debug:
    msg:
      - '{{ npm_path }}{{ var_yarn }}'
- name: Ensure that path is on the global PATH
  win_path:
    elements:
      - '{{ npm_path }}'
