version: 1

config:
  mysql:
    server: 192.168.1.100
    user: admintools
    password: gAAAAABiqLwtyGjmkWNN9t1RXcI3fQICccd-Ou8dR9Kw0uuZzti2MyqmMn6upXI0-gYwcK3LDWl8zZ-s0IXGsLrkO_-1wgnq9Txk09GxVfC0wYIQgqzdwCA=
    sql: SELECT host, mac FROM AdminTools.mac WHERE mac LIKE '%__mac__%'
  domain:
    domainname: schule.local
    admin: SCHULE\\Administrator
    passwd: gAAAAABg-r6nVT9sybCVtJ39F9B97bWCf1_QFodOYBuwmLK8rbsuG-kd1p0l-S30kntS7N-8LCQTTXjEoXIQAGHT2hBFMY-tsQ==
  local:
    admin: localhost\\kustos
    passwd: gAAAAABg-r68DND-uVF_AIR2hupkd-8folIIq7Axk-xhrvpQwP99wbaoLFHWE5gROGltdFndSDz4jWk2ONIJfJY13UneQeLvQg==
  kms: yes
