---
- name: Install needed modules
  pip:
    name:
      - psutil 
      - gputil 
      - tabulate 
      - wmi

 run python collect data
 
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts
