version: 1
config:
  # 1 = Debug mode, no script will be executed
  DEBUG: 1
ad:
  # where are your users in the forrest
  OU_BENUTZER: OU=Benutzer,DC=schule,DC=local

  # which Drive to map the profile to
  HOME_DRIVE: "Z:"
  HOME_PATH: S:\PDC\homes
  PROFILE_PATH: S:\PDC\profiles

  # initial Passsword
  INIT_PWD: Newton123
