version: 1
config:
  USE_SHARE: 1
  LOCAL_PATH: wallpapers\
  LOCAL_STORAGE: tmp\
  LAST: 10775_1600x1200-wallpaper-cb1268088745.jpg
  share:
    PATH: \\toolbox\Common
    USER: schule\common
    PWD: gAAAAABjfJ6BteZYzJtB_w4mwwvEUciu6uddhUqnGP92G3fJAEPNXEWGLUBKOC8_dnrIs8HuefKp8acKMAlABM0Z1Nc3ZtmOhw==
    7jhfM4Hizae8DiDN
