version: 1
config:
  # if set, then we use a Network Share for loading wallpapers
  # otherwise, we use a path relative to script dir
  USE_SHARE: 1
  # local path to wallpapers
  LOCAL_PATH: wallpapers\
  # where to store the wallpapers
  LOCAL_STORAGE: tmp\
  # last wallpaper
  LAST: None
  
  share:
    PATH: \\192.168.1.10\Public\wallpapers
    # if USER and PWS is empty, no credidentials will be used
    USER: 
    # hash the password with --encrypt Parameter
    PWD: 
  
