version: 1
config:
  # if set, then we use SFTP for loading wallpapers
  # otherwise, we use a path relative to script dir
  USE_SFTP: 1
  # local path to wallpapers
  LOCAL_PATH: wallpapers\
  # where to store the wallpapers
  LOCAL_STORAGE: tmp\
  # last wallpaper
  LAST: None
  
  sftp:
    HOSTNAME: toolbox
    PATH: wallpapers
    # if USER and PWS is empty, no credidentials will be used
    USER: common-mount
    # hash the password with --encrypt Parameter
    PWD: gAAAAABjlvlH4jX7OqlRvStofeB8uiQ1-egQRFWNUj_iE8WIZGeX_PX192CuPDRyKkdatAJy2QKV2lo0Q0GbpI-qmXR24S8iL8b4JOJQ3UQIQI40W8lOvK0=
  
    