version: 1

ad:
  # OU Benutzer
  OU_BENUTZER: OU=Benutzer,OU=Frauengasse,DC=schule,DC=local
  # OU Lehrer
  OU_LEHRER: OU=Lehrer

  HOME_PATH: D:\PDC\homes
  PROFILE_PATH: D:\PDC\profiles

  #initial Passsword
  INIT_PWD=Newton123
