version: 1
config:
  # dont do anything?
  DEBUG: 1
ad:
  # where are your users in the forrest
  OU_BENUTZER: OU=Benutzer,OU=Frauengasse,DC=schule,DC=local

  # which Drive to map the profile to
  HOME_DRIVE: "Z:"
  HOME_PATH: D:\PDC\homes
  PROFILE_PATH: D:\PDC\profiles

  # initial Passsword
  INIT_PWD: Newton123
