---
# Admin Users --------------------------------
# use global vars or local vars
- set_fact:
    pwd: '{{ item.0.password if ((global_admin_password is not defined) or (global_admin_password|length == 0)) else global_admin_password }}'

- name: Create Admin Users
  ansible.windows.win_user:
    name: '{{ item.0.name }}'
    password: '{{ pwd }}'
    state: present
    password_never_expires: true
    groups: '{{ item.1 }}'

- name: Debug
  debug:
    msg: 'User: {{ item.0.name }} > Group: {{ item.1 }}'
