---
# Admin Users --------------------------------
- name: Create Admin Users
  include_tasks: admins.yml
  loop: "{{ admins|subelements('groups') if admins is iterable }}"
  loop_control:
    label: '{{ item.0.name }}'

# Users --------------------------------------
- name: Create Users
  include_tasks: users.yml
  loop: "{{ users|subelements('groups') if users is iterable }}"
  loop_control:
    label: '{{ item.0.name }}'
